# Subset of kurtosis-cdk's deployment parameters.
# https://github.com/0xPolygon/kurtosis-cdk/blob/main/params.yml

args:
  zkevm_node_image: 0xpolygon/cdk-validium-node:0.6.4-cdk.2
  zkevm_prover_image: hermeznetwork/zkevm-prover:v6.0.0
  zkevm_da_image: 0xpolygon/cdk-data-availability:0.0.7
  zkevm_agglayer_image: 0xpolygon/agglayer:0.1.1
  zkevm_bridge_service_image: hermeznetwork/zkevm-bridge-service:v0.4.2
