name: lint

on: push

env:
  PNPM_VERSION: '8' # https://www.npmjs.com/package/pnpm

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install dependencies
        run: pnpm install

      - name: Check for lint issues
        run: pnpm run check

      - name: Check for broken links
        run: pnpm run links
