name: lint

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    strategy:
      fail-fast: true
      matrix:
        version: [18]

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install npm dependencies
        run: npm ci
        id: install

      - name: Run lint on markdown files
        run: npx prettier --write '*.md' '**/*.md'
        id: readme-lint
