name: lint

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    strategy:
      fail-fast: true
      matrix:
        version: [18]

    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install npm dependencies
        run: npm ci
        id: install

      - name: Lint code
        run: npx prettier --check .
        id: lint-code

      - name: Lint tables
        run: npx markdown-table-formatter --check **/*.md
        id: lint-tables

  broken-links:
    strategy:
      fail-fast: true
      matrix:
        version: [18]

    name: Broken links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install npm dependencies
        run: npm ci
        id: install

      - name: Check for broken links
        run: make links
        id: links
